ra-41---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: test
# description will be included in the image's metadata
description: Still under construction

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: lastest #41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      - micro
      - alacritty
      - neovim
      - hyprland
      - xdg-dektop-portal-hyprland
      - waypaper
      - swww
      - hypridle
      - hyprlock
      - waybar
      - rofi-wayland
      - tmux
      - nemo
      - distrobox
      - polkit-gnome
      - gimp
      - blender
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
